//
//  LocalizationManager.swift
//  LogiScan
//
//  Created by GitHub Copilot on 13/11/2025.
//

import SwiftUI
import Combine

/// Gestionnaire centralisé pour la localisation de l'application
class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @Published var currentLanguage: AppLanguage {
        didSet {
            saveLanguage()
            // Forcer la mise à jour de l'interface
            objectWillChange.send()
        }
    }
    
    private let languageKey = "app_language"
    
    private init() {
        // Charger la langue sauvegardée ou utiliser français par défaut
        if let savedLanguage = UserDefaults.standard.string(forKey: languageKey),
           let language = AppLanguage(rawValue: savedLanguage) {
            self.currentLanguage = language
        } else {
            self.currentLanguage = .french
        }
    }
    
    /// Change la langue de l'application
    func setLanguage(_ language: AppLanguage) {
        currentLanguage = language
    }
    
    /// Synchronise la langue avec celle de l'entreprise
    func syncWithCompanyLanguage(_ companyLanguage: String) {
        if let language = AppLanguage(rawValue: companyLanguage) {
            setLanguage(language)
        }
    }
    
    /// Sauvegarde la langue dans UserDefaults
    private func saveLanguage() {
        UserDefaults.standard.set(currentLanguage.rawValue, forKey: languageKey)
    }
    
    /// Récupère une traduction pour une clé donnée
    func localize(_ key: String) -> String {
        return Translations.translate(key, language: currentLanguage)
    }
}

/// Extension pour faciliter l'accès aux traductions dans les vues
extension String {
    func localized() -> String {
        return LocalizationManager.shared.localize(self)
    }
}

/// Structure contenant toutes les traductions de l'application
struct Translations {
    static func translate(_ key: String, language: AppLanguage) -> String {
        let translations: [String: String]
        
        switch language {
        case .english:
            translations = englishTranslations
        case .mandarin:
            translations = mandarinTranslations
        case .hindi:
            translations = hindiTranslations
        case .spanish:
            translations = spanishTranslations
        case .french:
            translations = frenchTranslations
        case .arabic:
            translations = arabicTranslations
        case .russian:
            translations = russianTranslations
        case .portuguese:
            translations = portugueseTranslations
        case .bengali:
            translations = bengaliTranslations
        case .german:
            translations = germanTranslations
        case .italian:
            translations = italianTranslations
        case .dutch:
            translations = dutchTranslations
        }
        
        return translations[key] ?? key
    }
    
    // MARK: - Traductions Françaises
    private static let frenchTranslations: [String: String] = [
        // Général
        "cancel": "Annuler",
        "save": "Enregistrer",
        "saving": "Enregistrement...",
        "delete": "Supprimer",
        "edit": "Modifier",
        "close": "Fermer",
        "confirm": "Confirmer",
        "back": "Retour",
        "next": "Suivant",
        "previous": "Précédent",
        "search": "Rechercher",
        "filter": "Filtrer",
        "all": "Tous",
        "none": "Aucun",
        "yes": "Oui",
        "no": "Non",
        "loading": "Chargement...",
        "error": "Erreur",
        "success": "Succès",
        "warning": "Attention",
        "ok": "OK",
        "done": "Terminé",
        "add": "Ajouter",
        "remove": "Retirer",
        "update": "Mettre à jour",
        "refresh": "Actualiser",
        "send": "Envoyer",
        "copy": "Copier",
        "share": "Partager",
        "download": "Télécharger",
        "upload": "Téléverser",
        "preview": "Aperçu",
        "details": "Détails",
        "info": "Informations",
        "help": "Aide",
        "about": "À propos",
        "version": "Version",
        "copyright": "Droits d'auteur",
        "required": "Requis",
        "optional": "Optionnel",
        "name": "Nom",
        "description": "Description",
        "date": "Date",
        "time": "Heure",
        "status": "Statut",
        "type": "Type",
        "priority": "Priorité",
        "owner": "Propriétaire",
        "created": "Créé",
        "updated": "Mis à jour",
        "total": "Total",
        "count": "Nombre",
        "items": "Articles",
        "actions": "Actions",
        
        // Language change
        "language_changed": "Langue modifiée",
        "restart_required": "La langue de l'application a été changée. Les modifications seront appliquées immédiatement.",
        "restart_now": "OK",
        "restart_later": "Plus tard",
        
        // Auth
        "login": "Connexion",
        "signup": "Inscription",
        "logout": "Déconnexion",
        "sign_in": "Se connecter",
        "sign_up": "S'inscrire",
        "sign_out": "Se déconnecter",
        "email": "Email",
        "password": "Mot de passe",
        "confirm_password": "Confirmer le mot de passe",
        "forgot_password": "Mot de passe oublié ?",
        "reset_password": "Réinitialiser le mot de passe",
        "reset_password_instructions": "Entrez votre email pour recevoir un lien de réinitialisation",
        "send_reset_link": "Envoyer le lien",
        "create_account": "Créer un compte",
        "already_have_account": "Vous avez déjà un compte ?",
        "dont_have_account": "Vous n'avez pas de compte ?",
        "full_name": "Nom complet",
        "choose_account_type": "Choisissez votre type de compte",
        "your_information": "Vos informations",
        "enter_personal_info": "Entrez vos informations personnelles",
        "your_company": "Votre entreprise",
        "create_your_company": "Créez votre entreprise",
        "you_are_owner": "Vous êtes propriétaire",
        "you_are_employee": "Vous êtes employé",
        "ask_employer_code": "Demandez le code d'invitation à votre employeur",
        "min_6_characters": "Au moins 6 caractères",
        "passwords_match": "Les mots de passe correspondent",
        "add_logo": "Ajouter un logo",
        "change_logo": "Changer le logo",
        
        // Entreprise
        "company": "Entreprise",
        "my_company": "Mon Entreprise",
        "company_name": "Nom de l'entreprise",
        "company_email": "Email de l'entreprise",
        "company_phone": "Téléphone",
        "company_address": "Adresse",
        "company_siret": "SIRET",
        "company_language": "Langue de l'entreprise",
        "create_company": "Créer une entreprise",
        "join_company": "Rejoindre une entreprise",
        "invitation_code": "Code d'invitation",
        "enter_invitation_code": "Entrez le code d'invitation",
        "company_details": "Détails de l'entreprise",
        "company_info": "Informations de l'entreprise",
        
        // Rôles
        "role": "Rôle",
        "admin": "Admin",
        "manager": "Manager",
        "employee": "Employé",
        "limited_employee": "Employé limité",
        "administrator": "Administrateur",
        "permissions": "Permissions",
        
        // Dashboard
        "dashboard": "Tableau de bord",
        "statistics": "Statistiques",
        "recent_activity": "Activité récente",
        "quick_actions": "Actions rapides",
        "overview": "Aperçu",
        "reports": "Rapports",
        "analytics": "Analyses",
        "welcome": "Bienvenue",
        "hello": "Bonjour",
        
        // Stock
        "stock": "Stock",
        "inventory": "Inventaire",
        "add_item": "Ajouter un article",
        "edit_item": "Modifier l'article",
        "delete_item": "Supprimer l'article",
        "item_name": "Nom de l'article",
        "quantity": "Quantité",
        "location": "Emplacement",
        "category": "Catégorie",
        "sku": "SKU",
        "barcode": "Code-barres",
        "price": "Prix",
        "unit": "Unité",
        "supplier": "Fournisseur",
        "warehouse": "Entrepôt",
        "stock_level": "Niveau de stock",
        "low_stock": "Stock bas",
        "out_of_stock": "Rupture de stock",
        "in_stock": "En stock",
        "reorder": "Réapprovisionner",
        "reorder_level": "Seuil de réapprovisionnement",
        
        // Scanner
        "scanner": "Scanner",
        "scan": "Scanner",
        "scan_barcode": "Scanner un code-barres",
        "scan_qr_code": "Scanner un QR code",
        "camera_permission": "Permission caméra",
        "camera_permission_message": "L'accès à la caméra est nécessaire pour scanner",
        "scan_result": "Résultat du scan",
        "scan_again": "Scanner à nouveau",
        "scan_history": "Historique des scans",
        
        // Événements
        "events": "Événements",
        "event": "Événement",
        "new_event": "Nouvel événement",
        "event_name": "Nom de l'événement",
        "event_date": "Date",
        "event_location": "Lieu",
        "event_type": "Type d'événement",
        "start_date": "Date de début",
        "end_date": "Date de fin",
        "all_day": "Toute la journée",
        "organizer": "Organisateur",
        "participants": "Participants",
        "notes": "Notes",
        
        // Camions
        "trucks": "Camions",
        "truck": "Camion",
        "add_truck": "Ajouter un camion",
        "truck_name": "Nom du camion",
        "truck_plate": "Plaque d'immatriculation",
        "truck_status": "Statut",
        "license_plate": "Plaque d'immatriculation",
        "driver": "Chauffeur",
        "capacity": "Capacité",
        "model": "Modèle",
        "brand": "Marque",
        "year": "Année",
        
        // Tâches
        "tasks": "Tâches",
        "task": "Tâche",
        "new_task": "Nouvelle tâche",
        "task_title": "Titre de la tâche",
        "task_description": "Description",
        "task_priority": "Priorité",
        "task_status": "Statut",
        "due_date": "Date d'échéance",
        "assigned_to": "Assigné à",
        "created_by": "Créé par",
        "high_priority": "Priorité haute",
        "medium_priority": "Priorité moyenne",
        "low_priority": "Priorité basse",
        "urgent": "Urgent",
        
        // Paramètres
        "settings": "Paramètres",
        "profile": "Profil",
        "my_profile": "Mon Profil",
        "account_settings": "Paramètres du compte",
        "app_settings": "Paramètres de l'app",
        "language": "Langue",
        "theme": "Thème",
        "notifications": "Notifications",
        "privacy": "Confidentialité",
        "security": "Sécurité",
        "preferences": "Préférences",
        "general": "Général",
        "advanced": "Avancé",
        
        // Membres
        "members": "Membres",
        "member": "Membre",
        "add_member": "Ajouter un membre",
        "remove_member": "Retirer le membre",
        "member_details": "Détails du membre",
        "team": "Équipe",
        "users": "Utilisateurs",
        "user": "Utilisateur",
        
        // Codes d'invitation
        "invitation_codes": "Codes d'invitation",
        "generate_code": "Générer un code",
        "new_code": "Nouveau code",
        "active": "Actif",
        "inactive": "Inactif",
        "activate": "Activer",
        "deactivate": "Désactiver",
        "code_uses": "utilisations",
        "max_uses": "Utilisations max",
        "validity": "Validité",
        "expires_on": "Expire le",
        "never_expires": "N'expire jamais",
        
        // Gestion des données
        "data_management": "Gestion des données",
        "delete_all_trucks": "Supprimer tous les camions",
        "delete_all_stock": "Supprimer tout le stock",
        "delete_all_events": "Supprimer tous les événements",
        "delete_all_data": "Supprimer toutes les données",
        "export_data": "Exporter les données",
        "import_data": "Importer les données",
        "backup": "Sauvegarde",
        "restore": "Restaurer",
        
        // Messages de confirmation
        "logout_confirm": "Voulez-vous vraiment vous déconnecter ?",
        "delete_confirm": "Cette action est irréversible. Toutes les données seront supprimées.",
        "save_changes": "Enregistrer les modifications",
        "discard_changes": "Annuler les modifications",
        "unsaved_changes": "Modifications non enregistrées",
        "are_you_sure": "Êtes-vous sûr ?",
        "cannot_undo": "Cette action ne peut pas être annulée",
        
        // Statuts
        "available": "Disponible",
        "unavailable": "Indisponible",
        "in_use": "En cours d'utilisation",
        "maintenance": "Maintenance",
        "completed": "Terminé",
        "pending": "En attente",
        "in_progress": "En cours",
        "cancelled": "Annulé",
        "delayed": "Retardé",
        "on_time": "À l'heure",
        "late": "En retard",
        "early": "En avance",
        
        // Filtres
        "filter_by_category": "Filtrer par catégorie",
        "filter_by_status": "Filtrer par statut",
        "filter_by_location": "Filtrer par emplacement",
        "filter_by_date": "Filtrer par date",
        "filter_by_user": "Filtrer par utilisateur",
        "filter_by_priority": "Filtrer par priorité",
        "sort_by": "Trier par",
        "sort_by_name": "Trier par nom",
        "sort_by_date": "Trier par date",
        "sort_by_quantity": "Trier par quantité",
        "sort_by_priority": "Trier par priorité",
        "sort_ascending": "Ordre croissant",
        "sort_descending": "Ordre décroissant",
        "show_all": "Tout afficher",
        "show_active": "Afficher actifs",
        "show_archived": "Afficher archivés",
        
        // Dates et temps
        "today": "Aujourd'hui",
        "yesterday": "Hier",
        "tomorrow": "Demain",
        "this_week": "Cette semaine",
        "last_week": "Semaine dernière",
        "next_week": "Semaine prochaine",
        "this_month": "Ce mois",
        "last_month": "Mois dernier",
        "next_month": "Mois prochain",
        "this_year": "Cette année",
        "last_year": "Année dernière",
        "days": "jours",
        "weeks": "semaines",
        "months": "mois",
        "years": "années",
        "ago": "il y a",
        "from_now": "d'ici",
        
        // Messages d'erreur
        "error_occurred": "Une erreur s'est produite",
        "try_again": "Réessayer",
        "something_went_wrong": "Quelque chose s'est mal passé",
        "check_connection": "Vérifiez votre connexion",
        "no_internet": "Pas de connexion Internet",
        "invalid_email": "Email invalide",
        "invalid_password": "Mot de passe invalide",
        "passwords_dont_match": "Les mots de passe ne correspondent pas",
        "field_required": "Ce champ est requis",
        "invalid_format": "Format invalide",
        
        // Messages de succès
        "saved_successfully": "Enregistré avec succès",
        "deleted_successfully": "Supprimé avec succès",
        "updated_successfully": "Mis à jour avec succès",
        "created_successfully": "Créé avec succès",
        "sent_successfully": "Envoyé avec succès",
        "operation_successful": "Opération réussie",
        
        // Autres
        "view": "Voir",
        "open": "Ouvrir",
        "select": "Sélectionner",
        "selected": "Sélectionné",
        "unselect": "Désélectionner",
        "select_all": "Tout sélectionner",
        "clear_all": "Tout effacer",
        "apply": "Appliquer",
        "reset": "Réinitialiser",
        "clear": "Effacer",
        "more": "Plus",
        "less": "Moins",
        "show_more": "Afficher plus",
        "show_less": "Afficher moins",
        "expand": "Développer",
        "collapse": "Réduire",
        "full_screen": "Plein écran",
        "exit_full_screen": "Quitter plein écran",
        "print": "Imprimer",
        "export": "Exporter",
        "import": "Importer",
        
        // LoginView spécifique
        "app_tagline": "Gestion d'inventaire intelligente",
        "no_account_yet": "Pas encore de compte ?",
        
        // DashboardView spécifique
        "metrics": "Métriques",
        "synchronization": "Synchronisation...",
        "syncing": "Synchronisation en cours...",
        
        // ProfileView spécifique
        "my_tasks": "Mes tâches",
        "my_daily_tasks": "Mes tâches du jour",
        "available_tasks": "Tâches disponibles",
        "task_count": "tâches",
        "delete_account": "Supprimer le compte",
        "reauthenticate": "Réauthentification requise",
        "enter_credentials": "Entrez vos identifiants",
        "manage_tasks": "Gestion des Tâches",
        "create_task": "Créer une tâche",
        "manage_all_tasks": "Gérer toutes les tâches",
        "assign_tasks": "Attribuer des tâches",
        "task_management_description": "Créez et attribuez des tâches aux membres de votre équipe.",
        "my_tasks_description": "Gérez vos tâches personnelles et prenez des tâches en libre-service.",
        "manage_my_company": "Gérer mon entreprise",
        "full_administration": "Administration complète",
        "administration": "Administration",
        "delete_my_account": "Supprimer mon compte",
        
        // Stock spécifique
        "add_stock_item": "Ajouter un article",
        "stock_list": "Liste du stock",
        "no_items": "Aucun article",
        "no_items_in_stock": "Aucun article en stock",
        "add_first_item": "Commencez par ajouter votre premier article",
        "configure_new_item": "Configurer un nouvel article",
        "try_modify_filters": "Essayez de modifier vos filtres ou votre recherche",
        "reset_filters": "Réinitialiser les filtres",
        "print_qr_codes": "Imprimer les QR codes",
        "generate_print_qr": "Générez et imprimez des QR codes pour vos articles",
        "equipment_type": "Type de matériel",
        "categories": "Catégories",
        "tags": "Étiquettes",
        "only_used_tags_shown": "Seules les étiquettes utilisées sont affichées",
        "filters": "Filtres",
        "select_items_print": "Sélectionnez les articles et références à imprimer",
        "export_csv": "Exporter en CSV",
        "export_inventory_file": "Exportez votre inventaire dans un fichier",
        "sync_now": "Synchroniser maintenant",
        "last_sync": "Dernière synchro",
        "never_synced": "Jamais synchronisé",
        "available_actions": "Actions disponibles",
        "main_item": "Article principal",
        "qr_print_title": "Impression QR codes",
        "select_items_refs_qr": "Sélectionnez les articles et leurs références individuelles dont vous souhaitez imprimer les QR codes",
        
        // Events spécifique
        "event_details": "Détails de l'événement",
        "add_event": "Ajouter un événement",
        
        // Trucks spécifique
        "truck_list": "Liste des camions",
        "add_new_truck": "Ajouter un camion",
        
        // Scanner spécifique
        "scan_mode": "Mode de scan",
        "free_scan": "Scan libre",
        "event_scan": "Scan événement",
        "inventory_scan": "Scan inventaire",
        "scan_lists": "Listes de scan",
        "scan_asset": "Scanner un asset",
        "scan_success": "Scan réussi",
        "scan_error": "Erreur de scan",
        "camera_access": "Accès caméra",
        "camera_access_required": "L'accès à la caméra est requis pour scanner",
        "open_settings": "Ouvrir les paramètres",
        "scan_item": "Scanner un article",
        "scanning": "Scan en cours...",
        "tap_to_scan": "Appuyez pour scanner",
        "unknown_code": "Code inconnu",
        
        // Events additionnelles
        "no_events": "Aucun événement",
        "create_first_event": "Créez votre premier événement",
        "event_title": "Titre de l'événement",
        "client_name": "Nom du client",
        "delivery_date": "Date de livraison",
        "return_date": "Date de retour",
        "quote": "Devis",
        "cart": "Panier",
        "finalize_quote": "Finaliser le devis",
        "add_to_cart": "Ajouter au panier",
        "event_created": "Événement créé",
        "quote_version": "Version du devis",
        "history": "Historique",
        
        // Trucks additionnelles
        "no_trucks": "Aucun camion",
        "add_first_truck": "Ajoutez votre premier camion",
        "truck_details": "Détails du camion",
        "registration": "Immatriculation",
        "truck_model": "Modèle",
        "truck_brand": "Marque",
        "truck_year": "Année",
        "truck_capacity": "Capacité",
        "truck_driver": "Chauffeur",
        "truck_available": "Disponible",
        "truck_in_use": "En cours d'utilisation",
        "truck_maintenance": "En maintenance",
        "volume": "Volume",
        
        // Tasks additionnelles
        "task_list": "Liste des tâches",
        "create_new_task": "Créer une nouvelle tâche",
        "no_tasks": "Aucune tâche",
        "task_details": "Détails de la tâche",
        "task_assigned_to": "Assignée à",
        "task_created_by": "Créée par",
        "task_due_date": "Date d'échéance",
        "task_completed": "Tâche terminée",
        "mark_complete": "Marquer comme terminée",
        "mark_incomplete": "Marquer comme non terminée",
        "unassigned": "Non assigné",
        "assign_to_me": "M'assigner",
        "reassign": "Réassigner",
        "task_suggestions": "Suggestions de tâches",
        
        // Admin additionnelles
        "admin_dashboard": "Tableau de bord admin",
        "user_management": "Gestion des utilisateurs",
        "company_management": "Gestion de l'entreprise",
        "system_settings": "Paramètres système",
        "data_export": "Export des données",
        "data_import": "Import des données",
        "backup_restore": "Sauvegarde & Restauration",
        "logs": "Journaux",
        "permissions_management": "Gestion des permissions",
        
        // Actions communes
        "duplicate": "Dupliquer",
        "archive": "Archiver",
        "unarchive": "Désarchiver",
        "move": "Déplacer",
        "rename": "Renommer",
        "properties": "Propriétés",
        "visibility": "Visibilité",
        "public": "Public",
        "private": "Privé",
        "shared": "Partagé",
        
        // Dates
        "select_date": "Sélectionner une date",
        "select_time": "Sélectionner une heure",
        "date_range": "Plage de dates",
        "start_time": "Heure de début",
        "end_time": "Heure de fin",
        "duration": "Durée",
        "hour": "Heure",
        "minute": "Minute",
        "second": "Seconde",
        
        // Validation
        "min_length": "Longueur minimale",
        "max_length": "Longueur maximale",
        "must_be_positive": "Doit être positif",
        "must_be_number": "Doit être un nombre",
        
        // Succès
        "saved": "Enregistré",
        "deleted": "Supprimé",
        "sent": "Envoyé",
        "copied": "Copié",
        "shared_successfully": "Partagé avec succès",
        
        // Erreurs
        "error_loading": "Erreur de chargement",
        "error_saving": "Erreur d'enregistrement",
        "error_deleting": "Erreur de suppression",
        "network_error": "Erreur réseau",
        "permission_denied": "Permission refusée",
        "not_found": "Non trouvé",
        "already_exists": "Existe déjà",
        
        // Confirmations
        "delete_confirmation": "Êtes-vous sûr de vouloir supprimer cet élément ?",
        "archive_confirmation": "Êtes-vous sûr de vouloir archiver cet élément ?",
        "discard_changes_confirmation": "Voulez-vous abandonner les modifications ?",
        
        // États vides
        "no_data": "Aucune donnée",
        "empty_list": "Liste vide",
        "no_search_results": "Aucun résultat de recherche",
        "start_by_adding": "Commencez par ajouter",
        
        // Général
        "empty_state": "Aucune donnée disponible",
        "no_results": "Aucun résultat",
        "load_more": "Charger plus",
        
        // Dashboard clés additionnelles
        "test_data_created": "Données de test créées",
        "test_data_message": "Les données de test ont été créées et synchronisées avec Firebase.",
        "load_test_data": "Charger données test",
        "loading_data": "Chargement...",
        "debug_permissions": "Debug permissions",
        "active_assets": "Assets actifs",
        "stock_items": "Articles en stock",
        "total_stock": "Stock total",
        "movements_today": "Mouvements aujourd'hui",
        "stock_distribution": "Répartition du stock par catégorie",
        "no_recent_movements": "Aucun mouvement récent",
        "asset": "Asset",
        "new_order": "Nouvel ordre",
        "view_all": "Voir tout",

        // Clés supplémentaires
        "add_action": "Ajouter",
        "additional_info": "Informations complémentaires",
        "adjustment": "Ajustement",
        "advice": "Conseil",
        "agenda": "Agenda",
        "article": "Article",
        "assigned_truck": "Camion assigné",
        "automatic_actions": "Actions automatiques",
        "available_state": "disponible",
        "capacity_label": "Capacité",
        "change": "Changer",
        "characteristics": "Caractéristiques",
        "client_info": "Informations client",
        "cm": "cm",
        "code_generated": "Code généré",
        "comments": "Commentaires",
        "complete_list": "Liste complète",
        "consumption": "Consommation",
        "create_movement": "Créer mouvement",
        "current_context": "Contexte actuel",
        "current_state": "État actuel",
        "finish": "Terminer",
        "flash": "Flash",
        "format": "Format",
        "free": "Libre",
        "from_maintenance": "Depuis maintenance",
        "identification": "Identification",
        "individual_references": "Références individuelles",
        "items_count": "articles",
        "kg": "kg",
        "labels": "Étiquettes",
        "large_size": "Grande taille",
        "list": "Liste",
        "max_volume": "Volume maximum",
        "max_weight": "Poids maximum",
        "medium_size": "Taille moyenne",
        "month": "Mois",
        "never": "Jamais",
        "next_item": "Prochain article",
        "no_comments": "Aucun commentaire",
        "no_event": "Aucun événement",
        "no_labels": "Aucune étiquette",
        "no_movement": "Aucun mouvement",
        "no_role": "Aucun rôle",
        "none_feminine": "Aucune",
        "not_defined": "Non définie",
        "not_planned": "Non planifiée",
        "not_started": "Non démarrée",
        "planning": "Planification",
        "progression": "Progression",
        "quote_finalized": "Devis terminé",
        "recent_movements": "Mouvements récents",
        "remove_action": "Retirer",
        "scanned_code": "Code scanné",
        "small_size": "Petite taille",
        "specifications": "Spécifications",
        "substitute_items": "Articles substituables",
        "suggested_tags": "Tags suggérés",
        "technical_description": "Description technique",
        "technical_details": "Détails techniques",
        "to_maintenance": "Vers maintenance",
        "unit_value": "Valeur unitaire",
        "unit_volume": "Volume unitaire",
        "unit_weight": "Poids unitaire",
        "week": "Semaine",
        
        // Settings - Codes d'invitation
        "irreversible_actions": "Actions irréversibles. Utilisez avec précaution.",
        "invitation_information": "Informations",
        "code_name_optional": "Nom du code (optionnel)",
        "code_example_team": "Ex: 'Équipe Livraison', 'Nouveaux Stagiaires', etc.",
        "invitation_code_section": "Code d'invitation",
        "customize_code": "Personnaliser le code",
        "custom_code": "Code personnalisé",
        "code_example_custom": "Ex: 'LIVRAISON-2025', 'TEAM-A', etc.",
        "code_preview": "Aperçu",
        "auto_generated_code": "Code généré automatiquement",
        "role_permissions": "Permissions du rôle",
        "code_will_give_role": "Ce code donnera le rôle:",
        "permissions_included": "Permissions incluses:",
        "code_validity_info": "Le code expirera dans {0} jours et pourra être utilisé {1} fois maximum.",
        "ensure_unique_code": "⚠️ Assurez-vous que le code personnalisé est unique et facile à partager.",
        "generating": "Génération...",
        "generate": "Générer",
        "validity_days": "Validité: {0} jours",
        "remove_member_confirm": "Voulez-vous vraiment retirer {0} de votre entreprise ?",
    ]
    
    // MARK: - Traductions Anglaises
    private static let englishTranslations: [String: String] = [
        // General
        "cancel": "Cancel",
        "save": "Save",
        "saving": "Saving...",
        "delete": "Delete",
        "edit": "Edit",
        "close": "Close",
        "confirm": "Confirm",
        "back": "Back",
        "next": "Next",
        "previous": "Previous",
        "search": "Search",
        "filter": "Filter",
        "all": "All",
        "none": "None",
        "yes": "Yes",
        "no": "No",
        "loading": "Loading...",
        "error": "Error",
        "success": "Success",
        "warning": "Warning",
        
        // Language change
        "language_changed": "Language Changed",
        "restart_required": "The application language has been changed. Changes will be applied immediately.",
        "restart_now": "OK",
        "restart_later": "Later",
        
        // Auth
        "login": "Login",
        "signup": "Sign Up",
        "logout": "Logout",
        "email": "Email",
        "password": "Password",
        "confirm_password": "Confirm Password",
        "forgot_password": "Forgot Password?",
        "reset_password": "Reset Password",
        "reset_password_instructions": "Enter your email to receive a reset link",
        "send_reset_link": "Send Reset Link",
        "create_account": "Create Account",
        "already_have_account": "Already have an account?",
        "dont_have_account": "Don't have an account?",
        "full_name": "Full Name",
        "choose_account_type": "Choose your account type",
        "your_information": "Your Information",
        "enter_personal_info": "Enter your personal information",
        "your_company": "Your Company",
        "create_your_company": "Create your company",
        
        // Company
        "company": "Company",
        "my_company": "My Company",
        "company_name": "Company Name",
        "company_email": "Company Email",
        "company_phone": "Phone",
        "company_address": "Address",
        "company_siret": "SIRET",
        "company_language": "Company Language",
        "create_company": "Create My Company",
        "join_company": "Join a Company",
        "invitation_code": "Invitation Code",
        "enter_invitation_code": "Enter invitation code",
        
        // Roles
        "role": "Role",
        "admin": "Admin",
        "manager": "Manager",
        "employee": "Employee",
        "limited_employee": "Limited Employee",
        
        // Dashboard
        "dashboard": "Dashboard",
        "statistics": "Statistics",
        "recent_activity": "Recent Activity",
        "quick_actions": "Quick Actions",
        
        // Stock
        "stock": "Stock",
        "inventory": "Inventory",
        "add_item": "Add Item",
        "edit_item": "Edit Item",
        "delete_item": "Delete Item",
        "item_name": "Item Name",
        "quantity": "Quantity",
        "location": "Location",
        "category": "Category",
        "sku": "SKU",
        "barcode": "Barcode",
        
        // Scanner
        "scanner": "Scanner",
        "scan": "Scan",
        "scan_barcode": "Scan Barcode",
        "scan_qr_code": "Scan QR Code",
        "camera_permission": "Camera Permission",
        "camera_permission_message": "Camera access is required to scan",
        
        // Events
        "events": "Events",
        "event": "Event",
        "new_event": "New Event",
        "event_name": "Event Name",
        "event_date": "Date",
        "event_location": "Location",
        "event_type": "Event Type",
        
        // Trucks
        "trucks": "Trucks",
        "truck": "Truck",
        "add_truck": "Add Truck",
        "truck_name": "Truck Name",
        "truck_plate": "License Plate",
        "truck_status": "Status",
        
        // Tasks
        "tasks": "Tasks",
        "task": "Task",
        "new_task": "New Task",
        "task_title": "Task Title",
        "task_description": "Description",
        "task_priority": "Priority",
        "task_status": "Status",
        "due_date": "Due Date",
        
        // Settings
        "settings": "Settings",
        "profile": "My Profile",
        "my_profile": "My Profile",
        "account_settings": "Account Settings",
        "app_settings": "App Settings",
        "language": "Language",
        "theme": "Theme",
        "notifications": "Notifications",
        "privacy": "Privacy",
        
        // Members
        "members": "Members",
        "member": "Member",
        "add_member": "Add Member",
        "remove_member": "Remove Member",
        "member_details": "Member Details",
        
        // Invitation Codes
        "invitation_codes": "Invitation Codes",
        "generate_code": "Generate Code",
        "new_code": "New Code",
        "active": "Active",
        "inactive": "Inactive",
        "activate": "Activate",
        "deactivate": "Deactivate",
        "code_uses": "uses",
        
        // Data Management
        "data_management": "Data Management",
        "delete_all_trucks": "Delete All Trucks",
        "delete_all_stock": "Delete All Stock",
        "delete_all_events": "Delete All Events",
        "delete_all_data": "Delete All Data",
        
        // Confirmation Messages
        "logout_confirm": "Do you really want to log out?",
        "delete_confirm": "This action is irreversible. All data will be deleted.",
        "save_changes": "Save Changes",
        
        // Status
        "available": "Available",
        "unavailable": "Unavailable",
        "in_use": "In Use",
        "maintenance": "Maintenance",
        "completed": "Completed",
        "pending": "Pending",
        "in_progress": "In Progress",
        
        // Filters
        "filter_by_category": "Filter by Category",
        "filter_by_status": "Filter by Status",
        "filter_by_location": "Filter by Location",
        "filter_by_date": "Filter by Date",
        "sort_by": "Sort By",
        "sort_by_name": "Sort by Name",
        "sort_by_date": "Sort by Date",
        "sort_by_quantity": "Sort by Quantity",
        
        // LoginView specific
        "app_tagline": "Smart Inventory Management",
        "no_account_yet": "No account yet?",
        "sign_in": "Sign In",
        
        // DashboardView specific
        "metrics": "Metrics",
        "synchronization": "Synchronization...",
        "syncing": "Syncing...",
        
        // ProfileView specific
        "my_tasks": "My Tasks",
        "my_daily_tasks": "My Daily Tasks",
        "available_tasks": "Available Tasks",
        "task_count": "tasks",
        "delete_account": "Delete Account",
        "reauthenticate": "Reauthentication Required",
        "enter_credentials": "Enter your credentials",
        "manage_tasks": "Task Management",
        "create_task": "Create a Task",
        "manage_all_tasks": "Manage All Tasks",
        "assign_tasks": "Assign Tasks",
        "task_management_description": "Create and assign tasks to your team members.",
        "my_tasks_description": "Manage your personal tasks and take on self-service tasks.",
        "manage_my_company": "Manage My Company",
        "full_administration": "Full Administration",
        "administration": "Administration",
        "sign_out": "Sign Out",
        "delete_my_account": "Delete My Account",
        
        // Stock specific
        "add_stock_item": "Add Stock Item",
        "stock_list": "Stock List",
        "no_items": "No Items",
        "no_items_in_stock": "No items in stock",
        "add_first_item": "Start by adding your first item",
        "configure_new_item": "Configure a new item",
        "try_modify_filters": "Try modifying your filters or search",
        "reset_filters": "Reset Filters",
        "clear_all": "Clear All",
        "print_qr_codes": "Print QR Codes",
        "generate_print_qr": "Generate and print QR codes for your items",
        "equipment_type": "Equipment Type",
        "categories": "Categories",
        "tags": "Tags",
        "only_used_tags_shown": "Only used tags are shown",
        "filters": "Filters",
        "select_items_print": "Select items and references to print",
        "export_csv": "Export to CSV",
        "export_inventory_file": "Export your inventory to a file",
        "sync_now": "Sync Now",
        "last_sync": "Last Sync",
        "never_synced": "Never Synced",
        "available_actions": "Available Actions",
        "main_item": "Main Item",
        "qr_print_title": "QR Codes Printing",
        "select_items_refs_qr": "Select items and their individual references for which you want to print QR codes",
        
        // Events specific
        "event_details": "Event Details",
        "add_event": "Add Event",
        
        // Trucks specific
        "truck_list": "Truck List",
        "add_new_truck": "Add New Truck",
        
        // Scanner specific
        "scan_mode": "Scan Mode",
        "free_scan": "Free Scan",
        "event_scan": "Event Scan",
        "inventory_scan": "Inventory Scan",
        "scan_lists": "Scan Lists",
        "scan_asset": "Scan Asset",
        "scan_success": "Scan Successful",
        "scan_error": "Scan Error",
        "camera_access": "Camera Access",
        "camera_access_required": "Camera access is required to scan",
        "open_settings": "Open Settings",
        "scan_item": "Scan Item",
        "scanning": "Scanning...",
        "tap_to_scan": "Tap to Scan",
        "scan_result": "Scan Result",
        "unknown_code": "Unknown Code",
        
        // Events additional
        "no_events": "No Events",
        "create_first_event": "Create Your First Event",
        "event_title": "Event Title",
        "client_name": "Client Name",
        "delivery_date": "Delivery Date",
        "return_date": "Return Date",
        "quote": "Quote",
        "cart": "Cart",
        "finalize_quote": "Finalize Quote",
        "add_to_cart": "Add to Cart",
        "event_created": "Event Created",
        "quote_version": "Quote Version",
        "history": "History",
        
        // Trucks additional
        "no_trucks": "No Trucks",
        "add_first_truck": "Add Your First Truck",
        "truck_details": "Truck Details",
        "registration": "Registration",
        "truck_model": "Model",
        "truck_brand": "Brand",
        "truck_year": "Year",
        "truck_capacity": "Capacity",
        "truck_driver": "Driver",
        "truck_available": "Available",
        "truck_in_use": "In Use",
        "truck_maintenance": "Under Maintenance",
        "volume": "Volume",
        "capacity": "Capacity",
        
        // Tasks additional
        "task_list": "Task List",
        "create_new_task": "Create New Task",
        "no_tasks": "No Tasks",
        "task_details": "Task Details",
        "task_assigned_to": "Assigned To",
        "task_created_by": "Created By",
        "task_due_date": "Due Date",
        "task_completed": "Task Completed",
        "mark_complete": "Mark as Complete",
        "mark_incomplete": "Mark as Incomplete",
        "unassigned": "Unassigned",
        "assign_to_me": "Assign to Me",
        "reassign": "Reassign",
        "task_suggestions": "Task Suggestions",
        
        // Admin additional
        "admin_dashboard": "Admin Dashboard",
        "user_management": "User Management",
        "company_management": "Company Management",
        "system_settings": "System Settings",
        "data_export": "Data Export",
        "data_import": "Data Import",
        "backup_restore": "Backup & Restore",
        "logs": "Logs",
        "permissions_management": "Permissions Management",
        
        // Common actions
        "duplicate": "Duplicate",
        "archive": "Archive",
        "unarchive": "Unarchive",
        "move": "Move",
        "rename": "Rename",
        "properties": "Properties",
        "visibility": "Visibility",
        "public": "Public",
        "private": "Private",
        "shared": "Shared",
        
        // Dates
        "select_date": "Select Date",
        "select_time": "Select Time",
        "date_range": "Date Range",
        "start_time": "Start Time",
        "end_time": "End Time",
        "duration": "Duration",
        "hour": "Hour",
        "minute": "Minute",
        "second": "Second",
        
        // Validation
        "invalid_email": "Invalid Email",
        "invalid_format": "Invalid Format",
        "min_length": "Minimum Length",
        "max_length": "Maximum Length",
        "must_be_positive": "Must Be Positive",
        "must_be_number": "Must Be a Number",
        
        // Success
        "saved": "Saved",
        "deleted": "Deleted",
        "updated": "Updated",
        "created": "Created",
        "sent": "Sent",
        "copied": "Copied",
        "shared_successfully": "Shared Successfully",
        
        // Errors
        "error_loading": "Error Loading",
        "error_saving": "Error Saving",
        "error_deleting": "Error Deleting",
        "network_error": "Network Error",
        "permission_denied": "Permission Denied",
        "not_found": "Not Found",
        "already_exists": "Already Exists",
        
        // Confirmations
        "delete_confirmation": "Are you sure you want to delete this item?",
        "archive_confirmation": "Are you sure you want to archive this item?",
        "discard_changes_confirmation": "Do you want to discard changes?",
        
        // Empty states
        "no_data": "No Data",
        "empty_list": "Empty List",
        "no_search_results": "No Search Results",
        "start_by_adding": "Start by Adding",
        
        // General
        "empty_state": "No data available",
        "no_results": "No results",
        "load_more": "Load More",
        
        // Dashboard additional keys
        "test_data_created": "Test Data Created",
        "test_data_message": "Test data has been created and synced with Firebase.",
        "load_test_data": "Load Test Data",
        "loading_data": "Loading...",
        "debug_permissions": "Debug Permissions",
        "active_assets": "Active Assets",
        "stock_items": "Stock Items",
        "total_stock": "Total Stock",
        "movements_today": "Movements Today",
        "stock_distribution": "Stock Distribution by Category",
        "no_recent_movements": "No Recent Movements",
        "asset": "Asset",
        "new_order": "New Order",
        "view_all": "View All",

        // Additional keys
        "add_action": "Add",
        "additional_info": "Additional Information",
        "adjustment": "Adjustment",
        "advice": "Advice",
        "agenda": "Agenda",
        "article": "Article",
        "assigned_truck": "Assigned Truck",
        "automatic_actions": "Automatic Actions",
        "available_state": "available",
        "capacity_label": "Capacity",
        "change": "Change",
        "characteristics": "Characteristics",
        "client_info": "Client Information",
        "cm": "cm",
        "code_generated": "Code Generated",
        "comments": "Comments",
        "complete_list": "Complete List",
        "consumption": "Consumption",
        "create_movement": "Create Movement",
        "current_context": "Current Context",
        "current_state": "Current State",
        "finish": "Finish",
        "flash": "Flash",
        "format": "Format",
        "free": "Free",
        "from_maintenance": "From Maintenance",
        "identification": "Identification",
        "individual_references": "Individual References",
        "items_count": "items",
        "kg": "kg",
        "labels": "Labels",
        "large_size": "Large Size",
        "list": "List",
        "max_volume": "Maximum Volume",
        "max_weight": "Maximum Weight",
        "medium_size": "Medium Size",
        "month": "Month",
        "never": "Never",
        "next_item": "Next Item",
        "no_comments": "No Comments",
        "no_event": "No Event",
        "no_labels": "No Labels",
        "no_movement": "No Movement",
        "no_role": "No Role",
        "none_feminine": "None",
        "not_defined": "Not Defined",
        "not_planned": "Not Planned",
        "not_started": "Not Started",
        "planning": "Planning",
        "progression": "Progress",
        "quote_finalized": "Quote Finalized",
        "recent_movements": "Recent Movements",
        "remove_action": "Remove",
        "scanned_code": "Scanned Code",
        "small_size": "Small Size",
        "specifications": "Specifications",
        "substitute_items": "Substitute Items",
        "suggested_tags": "Suggested Tags",
        "technical_description": "Technical Description",
        "technical_details": "Technical Details",
        "to_maintenance": "To Maintenance",
        "unit_value": "Unit Value",
        "unit_volume": "Unit Volume",
        "unit_weight": "Unit Weight",
        "week": "Week",
        
        // Settings - Invitation Codes
        "irreversible_actions": "Irreversible actions. Use with caution.",
        "invitation_information": "Information",
        "code_name_optional": "Code name (optional)",
        "code_example_team": "Ex: 'Delivery Team', 'New Interns', etc.",
        "invitation_code_section": "Invitation Code",
        "customize_code": "Customize code",
        "custom_code": "Custom code",
        "code_example_custom": "Ex: 'DELIVERY-2025', 'TEAM-A', etc.",
        "code_preview": "Preview",
        "auto_generated_code": "Auto-generated code",
        "role_permissions": "Role Permissions",
        "code_will_give_role": "This code will grant the role:",
        "permissions_included": "Permissions included:",
        "code_validity_info": "The code will expire in {0} days and can be used {1} times maximum.",
        "ensure_unique_code": "⚠️ Make sure the custom code is unique and easy to share.",
        "generating": "Generating...",
        "generate": "Generate",
        "validity_days": "Validity: {0} days",
        "remove_member_confirm": "Do you really want to remove {0} from your company?",
    ]
    
    // MARK: - Traductions Mandarin (中文)
    private static let mandarinTranslations: [String: String] = [
        "cancel": "取消",
        "save": "保存",
        "saving": "保存中...",
        "delete": "删除",
        "edit": "编辑",
        "close": "关闭",
        "confirm": "确认",
        "back": "返回",
        "next": "下一步",
        "search": "搜索",
        "filter": "过滤",
        "all": "全部",
        "loading": "加载中...",
        "settings": "设置",
        "my_profile": "我的资料",
        "my_company": "我的公司",
        "logout": "登出",
        "logout_confirm": "您确定要登出吗？",
        "language": "语言",
        "language_changed": "语言已更改",
        "restart_required": "请重新启动应用以应用语言更改。",
        "restart_now": "立即重启",
        "restart_later": "稍后",
        "members": "成员",
        "role": "角色",
        "admin": "管理员",
        "manager": "经理",
        "employee": "员工",
        "dashboard": "仪表板",
        "stock": "库存",
        "events": "活动",
        "trucks": "卡车",
        "tasks": "任务",
        "scanner": "扫描仪",
        "profile": "个人资料",
        "company_name": "公司名称",
        "company_language": "公司语言",
        "email": "电子邮件",
        "password": "密码",
        "confirm_password": "确认密码",
        "full_name": "全名",
        "create_account": "创建账户",
        "create_company": "创建公司",
        "join_company": "加入公司",
        "invitation_code": "邀请码",
        "company_email": "公司电子邮件",
        "company_phone": "电话",
        "company_address": "地址",
        "company_siret": "SIRET",
        "login": "登录",
        "signup": "注册",
        "sign_in": "登录",
        "sign_up": "注册",
    ]
    
    // MARK: - Traductions Hindi (हिन्दी)
    private static let hindiTranslations: [String: String] = [
        "cancel": "रद्द करें",
        "save": "सहेजें",
        "saving": "सहेजा जा रहा है...",
        "delete": "हटाएं",
        "edit": "संपादित करें",
        "close": "बंद करें",
        "confirm": "पुष्टि करें",
        "back": "वापस",
        "next": "अगला",
        "search": "खोजें",
        "filter": "फ़िल्टर करें",
        "all": "सभी",
        "loading": "लोड हो रहा है...",
        "settings": "सेटिंग्स",
        "my_profile": "मेरी प्रोफ़ाइल",
        "my_company": "मेरी कंपनी",
        "logout": "लॉग आउट",
        "logout_confirm": "क्या आप वाकई लॉग आउट करना चाहते हैं?",
        "language": "भाषा",
        "language_changed": "भाषा बदली गई",
        "restart_required": "कृपया भाषा परिवर्तन लागू करने के लिए ऐप को पुनः आरंभ करें।",
        "restart_now": "अभी पुनः आरंभ करें",
        "restart_later": "बाद में",
        "members": "सदस्य",
        "role": "भूमिका",
        "admin": "व्यवस्थापक",
        "manager": "प्रबंधक",
        "employee": "कर्मचारी",
        "dashboard": "डैशबोर्ड",
        "stock": "स्टॉक",
        "events": "कार्यक्रम",
        "trucks": "ट्रक",
        "tasks": "कार्य",
        "scanner": "स्कैनर",
        "profile": "प्रोफ़ाइल",
        "company_name": "कंपनी का नाम",
        "company_language": "कंपनी की भाषा",
        "email": "ईमेल",
        "password": "पासवर्ड",
        "confirm_password": "पासवर्ड की पुष्टि करें",
        "full_name": "पूरा नाम",
        "create_account": "खाता बनाएं",
        "create_company": "कंपनी बनाएं",
        "join_company": "कंपनी में शामिल हों",
        "invitation_code": "निमंत्रण कोड",
        "company_email": "कंपनी ईमेल",
        "company_phone": "फोन",
        "company_address": "पता",
        "company_siret": "SIRET",
        "login": "लॉगिन",
        "signup": "साइन अप",
        "sign_in": "साइन इन करें",
        "sign_up": "साइन अप करें",
    ]
    
    // MARK: - Traductions Bengali (বাংলা)
    private static let bengaliTranslations: [String: String] = [
        "cancel": "বাতিল",
        "save": "সংরক্ষণ",
        "saving": "সংরক্ষণ করা হচ্ছে...",
        "delete": "মুছুন",
        "edit": "সম্পাদনা",
        "close": "বন্ধ",
        "confirm": "নিশ্চিত করুন",
        "back": "ফিরে যান",
        "next": "পরবর্তী",
        "search": "অনুসন্ধান",
        "filter": "ফিল্টার",
        "all": "সব",
        "loading": "লোড হচ্ছে...",
        "settings": "সেটিংস",
        "my_profile": "আমার প্রোফাইল",
        "my_company": "আমার কোম্পানি",
        "logout": "লগ আউট",
        "logout_confirm": "আপনি কি সত্যিই লগ আউট করতে চান?",
        "language": "ভাষা",
        "language_changed": "ভাষা পরিবর্তিত",
        "restart_required": "দয়া করে ভাষা পরিবর্তন প্রয়োগ করতে অ্যাপ পুনরায় চালু করুন।",
        "restart_now": "এখনই পুনরায় চালু করুন",
        "restart_later": "পরে",
        "members": "সদস্য",
        "role": "ভূমিকা",
        "admin": "প্রশাসক",
        "manager": "ম্যানেজার",
        "employee": "কর্মচারী",
        "dashboard": "ড্যাশবোর্ড",
        "stock": "স্টক",
        "events": "ইভেন্ট",
        "trucks": "ট্রাক",
        "tasks": "কাজ",
        "scanner": "স্ক্যানার",
        "profile": "প্রোফাইল",
        "company_name": "কোম্পানির নাম",
        "company_language": "কোম্পানির ভাষা",
        "email": "ইমেইল",
        "password": "পাসওয়ার্ড",
        "confirm_password": "পাসওয়ার্ড নিশ্চিত করুন",
        "full_name": "পূর্ণ নাম",
        "create_account": "অ্যাকাউন্ট তৈরি করুন",
        "create_company": "কোম্পানি তৈরি করুন",
        "join_company": "কোম্পানিতে যোগ দিন",
        "invitation_code": "আমন্ত্রণ কোড",
        "company_email": "কোম্পানি ইমেইল",
        "company_phone": "ফোন",
        "company_address": "ঠিকানা",
        "company_siret": "SIRET",
        "login": "লগইন",
        "signup": "সাইন আপ",
        "sign_in": "সাইন ইন",
        "sign_up": "সাইন আপ করুন",
    ]
    private static let spanishTranslations: [String: String] = [
        // Common actions
        "cancel": "Cancelar",
        "save": "Guardar",
        "saving": "Guardando...",
        "delete": "Eliminar",
        "edit": "Editar",
        "close": "Cerrar",
        "confirm": "Confirmar",
        "back": "Atrás",
        "next": "Siguiente",
        "previous": "Anterior",
        "search": "Buscar",
        "filter": "Filtrar",
        "all": "Todos",
        "none": "Ninguno",
        "yes": "Sí",
        "no": "No",
        "loading": "Cargando...",
        "error": "Error",
        "success": "Éxito",
        "warning": "Advertencia",
        "ok": "OK",
        "done": "Hecho",
        "add": "Agregar",
        "remove": "Quitar",
        "update": "Actualizar",
        "refresh": "Actualizar",
        "send": "Enviar",
        "copy": "Copiar",
        "share": "Compartir",
        "download": "Descargar",
        "upload": "Subir",
        "preview": "Vista previa",
        "details": "Detalles",
        "info": "Información",
        "help": "Ayuda",
        "about": "Acerca de",
        "version": "Versión",
        "copyright": "Derechos de autor",
        "required": "Requerido",
        "optional": "Opcional",
        "name": "Nombre",
        "description": "Descripción",
        "date": "Fecha",
        "time": "Hora",
        "status": "Estado",
        "type": "Tipo",
        "priority": "Prioridad",
        "owner": "Propietario",
        "created": "Creado",
        "updated": "Actualizado",
        "total": "Total",
        "count": "Cantidad",
        "items": "Artículos",
        "actions": "Acciones",
        
        // Language change
        "language_changed": "Idioma cambiado",
        "restart_required": "El idioma de la aplicación ha sido cambiado. Los cambios se aplicarán inmediatamente.",
        "restart_now": "OK",
        "restart_later": "Más tarde",
        
        // Auth
        "login": "Iniciar sesión",
        "signup": "Registrarse",
        "logout": "Cerrar sesión",
        "sign_in": "Iniciar sesión",
        "sign_up": "Registrarse",
        "sign_out": "Cerrar sesión",
        "email": "Correo electrónico",
        "password": "Contraseña",
        "confirm_password": "Confirmar contraseña",
        "forgot_password": "¿Olvidaste tu contraseña?",
        "reset_password": "Restablecer contraseña",
        "reset_password_instructions": "Ingresa tu correo para recibir un enlace de restablecimiento",
        "send_reset_link": "Enviar enlace",
        "create_account": "Crear cuenta",
        "already_have_account": "¿Ya tienes una cuenta?",
        "dont_have_account": "¿No tienes una cuenta?",
        "full_name": "Nombre completo",
        "choose_account_type": "Elige tu tipo de cuenta",
        "your_information": "Tu información",
        "enter_personal_info": "Ingresa tu información personal",
        "your_company": "Tu empresa",
        "create_your_company": "Crea tu empresa",
        "you_are_owner": "Eres propietario",
        "you_are_employee": "Eres empleado",
        "ask_employer_code": "Solicita el código de invitación a tu empleador",
        "min_6_characters": "Mínimo 6 caracteres",
        "passwords_match": "Las contraseñas coinciden",
        "add_logo": "Agregar logo",
        "change_logo": "Cambiar logo",
        
        // Company
        "company": "Empresa",
        "my_company": "Mi Empresa",
        "company_name": "Nombre de la empresa",
        "company_email": "Correo de la empresa",
        "company_phone": "Teléfono",
        "company_address": "Dirección",
        "company_siret": "SIRET",
        "company_language": "Idioma de la empresa",
        "create_company": "Crear empresa",
        "join_company": "Unirse a empresa",
        "invitation_code": "Código de invitación",
        "enter_invitation_code": "Ingresa el código de invitación",
        "company_details": "Detalles de la empresa",
        
        // Navigation
        "dashboard": "Panel",
        "stock": "Inventario",
        "events": "Eventos",
        "trucks": "Camiones",
        "tasks": "Tareas",
        "scanner": "Escáner",
        "profile": "Perfil",
        "settings": "Configuración",
        "my_profile": "Mi Perfil",
        
        // Roles
        "admin": "Administrador",
        "manager": "Gerente",
        "employee": "Empleado",
        "limited_employee": "Empleado limitado",
        "role": "Rol",
        "members": "Miembros",
        "logout_confirm": "¿Realmente quieres cerrar sesión?",
        "language": "Idioma",
        
        // Stock & inventory  
        "active_assets": "Activos activos",
        "stock_items": "Artículos en stock",
        "total_stock": "Stock total",
        "equipment_type": "Tipo de equipo",
        "characteristics": "Características",
        "capacity": "Capacidad",
        "capacity_label": "Capacidad",
        "available_state": "disponible",
        "from_maintenance": "Desde mantenimiento",
        "cm": "cm",
        "individual_references": "Referencias individuales",
        "article": "Artículo",
        
        // Events
        "agenda": "Agenda",
        "client_info": "Información del cliente",
        "complete_list": "Lista completa",
        
        // Tasks
        "create_task": "Crear tarea",
        "assign_tasks": "Asignar tareas",
        "available_tasks": "Tareas disponibles",
        
        // Admin
        "administration": "Administración",
        "full_administration": "Administración completa",
        "debug_permissions": "Depurar permisos",
        "account_settings": "Configuración de cuenta",
        "data_management": "Gestión de datos",
        "delete_all_data": "Eliminar todos los datos",
        "delete_all_events": "Eliminar todos los eventos",
        "delete_all_stock": "Eliminar todo el stock",
        "delete_all_trucks": "Eliminar todos los camiones",
        "delete_my_account": "Eliminar mi cuenta",
        "irreversible_actions": "Acciones irreversibles",
        "delete_confirm": "¿Estás seguro?",
        
        // Invitations
        "invitation_information": "Información de invitación",
        "invitation_code_section": "Sección de código de invitación",
        "invitation_codes": "Códigos de invitación",
        "generate": "Generar",
        "generate_code": "Generar código",
        "generating": "Generando...",
        "code_generated": "Código generado",
        "code_preview": "Vista previa del código",
        "code_uses": "Usos del código",
        "code_name_optional": "Nombre del código (opcional)",
        "custom_code": "Código personalizado",
        "customize_code": "Personalizar código",
        "code_example_custom": "Ej: 'ENTREGA-2025', 'EQUIPO-A', etc.",
        "code_example_team": "Ej: 'Equipo de Entrega', 'Nuevos Pasantes', etc.",
        "code_validity_info": "El código expirará en {0} días y podrá usarse {1} veces como máximo.",
        "code_will_give_role": "Este código otorgará el rol:",
        "ensure_unique_code": "⚠️ Asegúrate de que el código personalizado sea único y fácil de compartir.",
        
        // Scanner
        "flash": "Flash",
        "finish": "Terminar",
        "filters": "Filtros",
        
        // Trucks
        "assigned_truck": "Camión asignado",
        
        // Common UI
        "change": "Cambiar",
        "activate": "Activar",
        "deactivate": "Desactivar",
        "format": "Formato",
        "advice": "Consejo",
        "comments": "Comentarios",
        "add_action": "Agregar",
        "additional_info": "Información adicional",
        "adjustment": "Ajuste",
        "automatic_actions": "Acciones automáticas",
        "available_actions": "Acciones disponibles",
        "clear_all": "Borrar todo",
        "categories": "Categorías",
        "configure_new_item": "Configurar nuevo artículo",
        "consumption": "Consumo",
        "create_movement": "Crear movimiento",
        "current_context": "Contexto actual",
        "current_state": "Estado actual",
        "identification": "Identificación",
        "add_first_item": "Agregar primer artículo",
        "empty_state": "Sin datos disponibles",
        "free": "Gratis",
        
        // Additional
        "app_tagline": "Tu aplicación de gestión",
        "test_data_created": "Datos de prueba creados",
        "test_data_message": "Los datos de prueba han sido creados y sincronizados con Firebase.",
        "load_test_data": "Cargar datos de prueba",
        "loading_data": "Cargando...",
        "movements_today": "Movimientos hoy",
        "stock_distribution": "Distribución del stock por categoría",
        "no_recent_movements": "Sin movimientos recientes",
        "asset": "Activo",
        "new_order": "Nuevo pedido",
        "view_all": "Ver todo",
    ]
    
    // MARK: - Traductions Portugaises
    private static let portugueseTranslations: [String: String] = [
        "cancel": "Cancelar",
        "save": "Guardar",
        "delete": "Eliminar",
        "edit": "Editar",
        "close": "Fechar",
        "confirm": "Confirmar",
        "back": "Voltar",
        "next": "Próximo",
        "search": "Pesquisar",
        "filter": "Filtrar",
        "all": "Todos",
        "loading": "Carregando...",
        "settings": "Configurações",
        "my_profile": "Meu Perfil",
        "my_company": "Minha Empresa",
        "logout": "Sair",
        "logout_confirm": "Você realmente quer sair?",
        "language": "Idioma",
        "members": "Membros",
        "role": "Função",
        "admin": "Admin",
        "manager": "Gerente",
        "employee": "Funcionário",
        "dashboard": "Painel",
        "stock": "Estoque",
        "events": "Eventos",
        "trucks": "Caminhões",
        "tasks": "Tarefas",
        "scanner": "Scanner",
        "profile": "Perfil",
        "company_name": "Nome da Empresa",
        "company_language": "Idioma da Empresa",
        "email": "E-mail",
        "password": "Senha",
        "full_name": "Nome Completo",
        "create_account": "Criar Conta",
        "create_company": "Criar Empresa",
        "join_company": "Entrar em Empresa",
        "invitation_code": "Código de Convite",
    ]
    
    // MARK: - Traductions Allemandes
    private static let germanTranslations: [String: String] = [
        // Common actions
        "cancel": "Abbrechen",
        "save": "Speichern",
        "saving": "Speichern...",
        "delete": "Löschen",
        "edit": "Bearbeiten",
        "close": "Schließen",
        "confirm": "Bestätigen",
        "back": "Zurück",
        "next": "Weiter",
        "previous": "Zurück",
        "search": "Suchen",
        "filter": "Filtern",
        "all": "Alle",
        "none": "Keine",
        "yes": "Ja",
        "no": "Nein",
        "loading": "Laden...",
        "error": "Fehler",
        "success": "Erfolg",
        "warning": "Warnung",
        "ok": "OK",
        "done": "Fertig",
        "add": "Hinzufügen",
        "remove": "Entfernen",
        "update": "Aktualisieren",
        "refresh": "Aktualisieren",
        "send": "Senden",
        "copy": "Kopieren",
        "share": "Teilen",
        "download": "Herunterladen",
        "upload": "Hochladen",
        "preview": "Vorschau",
        "details": "Details",
        "info": "Information",
        "help": "Hilfe",
        "about": "Über",
        "version": "Version",
        "copyright": "Urheberrecht",
        "required": "Erforderlich",
        "optional": "Optional",
        "name": "Name",
        "description": "Beschreibung",
        "date": "Datum",
        "time": "Zeit",
        "status": "Status",
        "type": "Typ",
        "priority": "Priorität",
        "owner": "Eigentümer",
        "created": "Erstellt",
        "updated": "Aktualisiert",
        "total": "Gesamt",
        "count": "Anzahl",
        "items": "Artikel",
        "actions": "Aktionen",
        
        // Language change
        "language_changed": "Sprache geändert",
        "restart_required": "Die Anwendungssprache wurde geändert. Die Änderungen werden sofort angewendet.",
        "restart_now": "OK",
        "restart_later": "Später",
        
        // Auth
        "login": "Anmelden",
        "signup": "Registrieren",
        "logout": "Abmelden",
        "sign_in": "Anmelden",
        "sign_up": "Registrieren",
        "sign_out": "Abmelden",
        "email": "E-Mail",
        "password": "Passwort",
        "confirm_password": "Passwort bestätigen",
        "forgot_password": "Passwort vergessen?",
        "reset_password": "Passwort zurücksetzen",
        "reset_password_instructions": "Geben Sie Ihre E-Mail ein, um einen Reset-Link zu erhalten",
        "send_reset_link": "Link senden",
        "create_account": "Konto erstellen",
        "already_have_account": "Haben Sie bereits ein Konto?",
        "dont_have_account": "Noch kein Konto?",
        "full_name": "Vollständiger Name",
        "choose_account_type": "Wählen Sie Ihren Kontotyp",
        "your_information": "Ihre Informationen",
        "enter_personal_info": "Geben Sie Ihre persönlichen Daten ein",
        "your_company": "Ihr Unternehmen",
        "create_your_company": "Erstellen Sie Ihr Unternehmen",
        "you_are_owner": "Sie sind Eigentümer",
        "you_are_employee": "Sie sind Mitarbeiter",
        "ask_employer_code": "Fragen Sie Ihren Arbeitgeber nach dem Einladungscode",
        "min_6_characters": "Mindestens 6 Zeichen",
        "passwords_match": "Passwörter stimmen überein",
        "add_logo": "Logo hinzufügen",
        "change_logo": "Logo ändern",
        
        // Company
        "company": "Unternehmen",
        "my_company": "Mein Unternehmen",
        "company_name": "Firmenname",
        "company_email": "Firmen-E-Mail",
        "company_phone": "Telefon",
        "company_address": "Adresse",
        "company_siret": "SIRET",
        "company_language": "Firmensprache",
        "create_company": "Firma erstellen",
        "join_company": "Firma beitreten",
        "invitation_code": "Einladungscode",
        "enter_invitation_code": "Einladungscode eingeben",
        "company_details": "Firmendetails",
        
        // Navigation
        "dashboard": "Dashboard",
        "stock": "Lager",
        "events": "Veranstaltungen",
        "trucks": "LKWs",
        "tasks": "Aufgaben",
        "scanner": "Scanner",
        "profile": "Profil",
        "settings": "Einstellungen",
        "my_profile": "Mein Profil",
        
        // Roles
        "admin": "Administrator",
        "manager": "Manager",
        "employee": "Mitarbeiter",
        "limited_employee": "Eingeschränkter Mitarbeiter",
        "role": "Rolle",
        "members": "Mitglieder",
        "logout_confirm": "Möchten Sie sich wirklich abmelden?",
        "language": "Sprache",
        
        // Stock & inventory
        "active_assets": "Aktive Assets",
        "stock_items": "Lagerartikel",
        "total_stock": "Gesamtbestand",
        "equipment_type": "Gerätetyp",
        "characteristics": "Eigenschaften",
        "capacity": "Kapazität",
        "capacity_label": "Kapazität",
        "available_state": "verfügbar",
        "from_maintenance": "Aus Wartung",
        "cm": "cm",
        "individual_references": "Einzelreferenzen",
        "article": "Artikel",
        
        // Events
        "agenda": "Agenda",
        "client_info": "Kundeninformationen",
        "complete_list": "Vollständige Liste",
        
        // Tasks
        "create_task": "Aufgabe erstellen",
        "assign_tasks": "Aufgaben zuweisen",
        "available_tasks": "Verfügbare Aufgaben",
        
        // Admin
        "administration": "Verwaltung",
        "full_administration": "Vollständige Verwaltung",
        "debug_permissions": "Berechtigungen debuggen",
        "account_settings": "Kontoeinstellungen",
        "data_management": "Datenverwaltung",
        "delete_all_data": "Alle Daten löschen",
        "delete_all_events": "Alle Veranstaltungen löschen",
        "delete_all_stock": "Gesamten Bestand löschen",
        "delete_all_trucks": "Alle LKWs löschen",
        "delete_my_account": "Mein Konto löschen",
        "irreversible_actions": "Nicht rückgängig zu machende Aktionen",
        "delete_confirm": "Sind Sie sicher?",
        
        // Invitations
        "invitation_information": "Einladungsinformationen",
        "invitation_code_section": "Einladungscode-Bereich",
        "invitation_codes": "Einladungscodes",
        "generate": "Generieren",
        "generate_code": "Code generieren",
        "generating": "Generieren...",
        "code_generated": "Code generiert",
        "code_preview": "Code-Vorschau",
        "code_uses": "Code-Verwendungen",
        "code_name_optional": "Code-Name (optional)",
        "custom_code": "Benutzerdefinierter Code",
        "customize_code": "Code anpassen",
        "code_example_custom": "Z.B. 'LIEFERUNG-2025', 'TEAM-A', etc.",
        "code_example_team": "Z.B. 'Lieferteam', 'Neue Praktikanten', etc.",
        "code_validity_info": "Der Code läuft in {0} Tagen ab und kann maximal {1} Mal verwendet werden.",
        "code_will_give_role": "Dieser Code gewährt die Rolle:",
        "ensure_unique_code": "⚠️ Stellen Sie sicher, dass der benutzerdefinierte Code eindeutig und leicht zu teilen ist.",
        
        // Scanner
        "flash": "Blitz",
        "finish": "Fertig",
        "filters": "Filter",
        
        // Trucks
        "assigned_truck": "Zugewiesener LKW",
        
        // Common UI
        "change": "Ändern",
        "activate": "Aktivieren",
        "deactivate": "Deaktivieren",
        "format": "Format",
        "advice": "Hinweis",
        "comments": "Kommentare",
        "add_action": "Hinzufügen",
        "additional_info": "Zusätzliche Informationen",
        "adjustment": "Anpassung",
        "automatic_actions": "Automatische Aktionen",
        "available_actions": "Verfügbare Aktionen",
        "clear_all": "Alles löschen",
        "categories": "Kategorien",
        "configure_new_item": "Neuen Artikel konfigurieren",
        "consumption": "Verbrauch",
        "create_movement": "Bewegung erstellen",
        "current_context": "Aktueller Kontext",
        "current_state": "Aktueller Status",
        "identification": "Identifikation",
        "add_first_item": "Ersten Artikel hinzufügen",
        "empty_state": "Keine Daten verfügbar",
        "free": "Kostenlos",
        
        // Additional
        "app_tagline": "Ihre Verwaltungsanwendung",
        "test_data_created": "Testdaten erstellt",
        "test_data_message": "Die Testdaten wurden erstellt und mit Firebase synchronisiert.",
        "load_test_data": "Testdaten laden",
        "loading_data": "Laden...",
        "movements_today": "Bewegungen heute",
        "stock_distribution": "Bestandsverteilung nach Kategorie",
        "no_recent_movements": "Keine aktuellen Bewegungen",
        "asset": "Asset",
        "new_order": "Neue Bestellung",
        "view_all": "Alle anzeigen",
    ]
    
    // MARK: - Traductions Russes
    private static let russianTranslations: [String: String] = [
        "cancel": "Отмена",
        "save": "Сохранить",
        "delete": "Удалить",
        "edit": "Редактировать",
        "close": "Закрыть",
        "confirm": "Подтвердить",
        "back": "Назад",
        "next": "Далее",
        "search": "Поиск",
        "filter": "Фильтр",
        "all": "Все",
        "loading": "Загрузка...",
        "settings": "Настройки",
        "my_profile": "Мой Профиль",
        "my_company": "Моя Компания",
        "logout": "Выйти",
        "logout_confirm": "Вы действительно хотите выйти?",
        "language": "Язык",
        "members": "Участники",
        "role": "Роль",
        "admin": "Админ",
        "manager": "Менеджер",
        "employee": "Сотрудник",
        "dashboard": "Панель",
        "stock": "Склад",
        "events": "События",
        "trucks": "Грузовики",
        "tasks": "Задачи",
        "scanner": "Сканер",
        "profile": "Профиль",
        "company_name": "Название компании",
        "company_language": "Язык компании",
        "email": "Электронная почта",
        "password": "Пароль",
        "full_name": "Полное имя",
        "create_account": "Создать аккаунт",
        "create_company": "Создать компанию",
        "join_company": "Присоединиться к компании",
        "invitation_code": "Код приглашения",
    ]
    
    // MARK: - Traductions Arabes
    private static let arabicTranslations: [String: String] = [
        "cancel": "إلغاء",
        "save": "حفظ",
        "delete": "حذف",
        "edit": "تعديل",
        "close": "إغلاق",
        "confirm": "تأكيد",
        "back": "رجوع",
        "next": "التالي",
        "search": "بحث",
        "filter": "تصفية",
        "all": "الكل",
        "loading": "جاري التحميل...",
        "settings": "الإعدادات",
        "my_profile": "ملفي الشخصي",
        "my_company": "شركتي",
        "logout": "تسجيل الخروج",
        "logout_confirm": "هل تريد حقاً تسجيل الخروج؟",
        "language": "اللغة",
        "members": "الأعضاء",
        "role": "الدور",
        "admin": "مدير",
        "manager": "مدير",
        "employee": "موظف",
        "dashboard": "لوحة القيادة",
        "stock": "المخزون",
        "events": "الأحداث",
        "trucks": "الشاحنات",
        "tasks": "المهام",
        "scanner": "الماسح",
        "profile": "الملف الشخصي",
        "company_name": "اسم الشركة",
        "company_language": "لغة الشركة",
        "email": "البريد الإلكتروني",
        "password": "كلمة المرور",
        "full_name": "الاسم الكامل",
        "create_account": "إنشاء حساب",
        "create_company": "إنشاء شركة",
        "join_company": "الانضمام إلى شركة",
        "invitation_code": "رمز الدعوة",
    ]
    
    // MARK: - Traductions Italiennes (Italiano)
    private static let italianTranslations: [String: String] = [
        "cancel": "Annulla",
        "save": "Salva",
        "saving": "Salvataggio...",
        "delete": "Elimina",
        "edit": "Modifica",
        "close": "Chiudi",
        "confirm": "Conferma",
        "back": "Indietro",
        "next": "Avanti",
        "search": "Cerca",
        "filter": "Filtra",
        "all": "Tutti",
        "loading": "Caricamento...",
        "settings": "Impostazioni",
        "my_profile": "Il Mio Profilo",
        "my_company": "La Mia Azienda",
        "logout": "Esci",
        "logout_confirm": "Vuoi davvero uscire?",
        "language": "Lingua",
        "language_changed": "Lingua modificata",
        "restart_required": "Si prega di riavviare l'app per applicare le modifiche alla lingua.",
        "restart_now": "Riavvia ora",
        "restart_later": "Più tardi",
        "members": "Membri",
        "role": "Ruolo",
        "admin": "Admin",
        "manager": "Manager",
        "employee": "Dipendente",
        "dashboard": "Dashboard",
        "stock": "Magazzino",
        "events": "Eventi",
        "trucks": "Camion",
        "tasks": "Compiti",
        "scanner": "Scanner",
        "profile": "Profilo",
        "company_name": "Nome Azienda",
        "company_language": "Lingua Azienda",
        "email": "Email",
        "password": "Password",
        "confirm_password": "Conferma Password",
        "full_name": "Nome Completo",
        "create_account": "Crea Account",
        "create_company": "Crea Azienda",
        "join_company": "Unisciti ad Azienda",
        "invitation_code": "Codice Invito",
        "company_email": "Email Aziendale",
        "company_phone": "Telefono",
        "company_address": "Indirizzo",
        "company_siret": "SIRET",
        "login": "Accedi",
        "signup": "Registrati",
        "sign_in": "Accedi",
        "sign_up": "Registrati",
    ]
    
    // MARK: - Traductions Néerlandaises (Nederlands)
    private static let dutchTranslations: [String: String] = [
        "cancel": "Annuleren",
        "save": "Opslaan",
        "saving": "Opslaan...",
        "delete": "Verwijderen",
        "edit": "Bewerken",
        "close": "Sluiten",
        "confirm": "Bevestigen",
        "back": "Terug",
        "next": "Volgende",
        "search": "Zoeken",
        "filter": "Filteren",
        "all": "Alle",
        "loading": "Laden...",
        "settings": "Instellingen",
        "my_profile": "Mijn Profiel",
        "my_company": "Mijn Bedrijf",
        "logout": "Uitloggen",
        "logout_confirm": "Wilt u echt uitloggen?",
        "language": "Taal",
        "language_changed": "Taal gewijzigd",
        "restart_required": "Start de app opnieuw op om de taalwijzigingen toe te passen.",
        "restart_now": "Nu opnieuw starten",
        "restart_later": "Later",
        "members": "Leden",
        "role": "Rol",
        "admin": "Admin",
        "manager": "Manager",
        "employee": "Medewerker",
        "dashboard": "Dashboard",
        "stock": "Voorraad",
        "events": "Evenementen",
        "trucks": "Vrachtwagens",
        "tasks": "Taken",
        "scanner": "Scanner",
        "profile": "Profiel",
        "company_name": "Bedrijfsnaam",
        "company_language": "Bedrijfstaal",
        "email": "E-mail",
        "password": "Wachtwoord",
        "confirm_password": "Bevestig Wachtwoord",
        "full_name": "Volledige Naam",
        "create_account": "Account Aanmaken",
        "create_company": "Bedrijf Aanmaken",
        "join_company": "Bedrijf Toetreden",
        "invitation_code": "Uitnodigingscode",
        "company_email": "Bedrijfs E-mail",
        "company_phone": "Telefoon",
        "company_address": "Adres",
        "company_siret": "SIRET",
        "login": "Inloggen",
        "signup": "Aanmelden",
        "sign_in": "Inloggen",
        "sign_up": "Aanmelden",
    ]
}
